name: Android Build SIMAGU

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Pasang Logo Aplikasi
      run: |
        mkdir -p app/src/main/res/drawable
        cp logo.jpg app/src/main/res/drawable/logo.jpg
        sed -i 's/<application/<application android:icon="@drawable\/logo" android:roundIcon="@drawable\/logo"/g' app/src/main/AndroidManifest.xml

    - name: Generate Gradle Wrapper v8.4
      run: gradle wrapper --gradle-version 8.4

    - name: Build Debug APK with Gradle Wrapper
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: SIMAGU-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
